services:
    enqueue.messenger_transport.factory:
        class: 'Enqueue\MessengerAdapter\QueueInteropTransportFactory'
        arguments:
            - "@messenger.transport.decoder"
            - "@messenger.transport.encoder"
            - "@service_container"
            - "%kernel.debug%"
        tags:
            - 'messenger.transport_factory'
