services:
    enqueue.messenger_transport.factory:
        class: 'Enqueue\MessengerAdapter\QueueInteropTransportFactory'
        arguments:
            - '@messenger.transport.serializer'
            - '@enqueue.locator'
            - '%kernel.debug%'
        tags: ['messenger.transport_factory']
